
# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - 2D image
  - 3D image
  - Cell segmentation
  - Connected-component analysis
  - Illumination correction
  - Image correction
  - Image denoising
  - Image thresholding
  - Pixel classification
  - Object classification
  - Image enhancement
